version: '3.8'
services:
  db:
    image: alextran0899/laser-tech-db
    environment:
      POSTGRES_DB: LaserTech
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
        
  backend:
    image: alextran0899/laser-tech-back-end
    network_mode: "host"
    depends_on:
      - db

  frontend:
    image: alextran0899/laser-tech-front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend